name: 📚 Docs (MkDocs)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: write   # needed for gh-pages push

concurrency:
  group: mkdocs-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # allow mkdocs-material to read git info if needed

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs toolchain
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.6.1 mkdocs-material==9.5.39

      - name: Build MkDocs site
        run: mkdocs build --strict --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # keep history allows custom 404s and CNAME persistence
          keep_files: false
          force_orphan: false
          full_commit_message: "docs: deploy MkDocs site from ${{ github.sha }}"
